Repository bounswe/2021SpringGroup3, pull requests merged in 2021-06, with the labels that each got.

#99 Community Entity and Creating Community API
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/CreateCommunityController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/utils/DetectLanguageApi.java
Labels: Component: Backend, Status: Review Needed, Type: Feature

#96 Profile Entity and Update Profile Function
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/user/CreateUserController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/Profile.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/UserEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/repository/ProfileRepository.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/ProfileService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/UserService.java
Labels: Component: Backend, Status: Review Needed

#101 Implemented API functionality: Creating Post and Fetching Places
  practiceapp/.gitignore
  practiceapp/pom.xml
  practiceapp/src/main/java/com/practiceapp/practiceapp/PracticeappApplication.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/places/GetPlacesController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/post/CreatePostController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/PostEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/PostService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/utils/PlacesApi.java
Labels: Component: Backend, Status: Review Needed

#100 Implemented api functionality: Getting post by a community
  practiceapp/pom.xml
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/GetPostsController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/utils/DictionaryApi.java
Labels: Component: Backend, Status: Review Needed

#104 Implemented api functionality: Joining Community
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/advice/AdviceController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/joining/JoiningCommunityController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/user/CreateUserController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/UserEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/repository/CommunityRepository.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/repository/UserRepository.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/JoiningCommunityService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/UserService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/utils/AdviceApi.java
Labels: Component: Backend, Status: Review Needed

#108 Profile Controller
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/profile/ProfileController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/user/CreateUserController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/utils/PicturesApi.java
Labels: Component: Backend, Status: Review Needed

#109 Update CommunityEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
Labels: Component: Backend, Type: Enhancement

#97 Implemented api functionality: Update Post
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/post/UpdatePostController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/user/CreateUserController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/repository/PostRepository.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/PostService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/UserService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/utils/KanyeRestApi.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/utils/LyricsApi.java
Labels: Component: Backend, Status: Review Needed

#111 Implemented API functionality: Get community by name
  practiceapp/pom.xml
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/GetCommunityController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/universitieslist/UniversitiesListController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/utils/UniversitiesListApi.java
Labels: Component: Backend, Status: Review Needed

#115 Updated CreatingCommunityController, Added Unit tests for the controller and community service
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/CreateCommunityController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/repository/CommunityRepository.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/utils/DetectLanguageApi.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/CreateCommunityControllerTest.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/service/CommunityServiceTest.java
Labels: Component: Backend, Component: Junit-Testing, Type: Enhancement

#119 JsonIgnore change and endpoint addition for getting joined / created communities.
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/joining/JoiningCommunityController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/user/CreateUserController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/UserEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/JoiningCommunityService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/UserService.java
Labels: Component: Backend, Status: Review Needed

#122 Get Posts By Controller / Community Entity
  practiceapp/pom.xml
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/GetPostsController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/PostService.java
Labels: Component: Backend, Status: Review Needed

#125 Implemented getCommunitiesByPublicityController
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/GetCommunitiesByPublicityController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
Labels: Component: Backend, Type: Feature

#135 Function Name Fix
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/profile/ProfileController.java
Labels: Component: Backend, Priority: Low, Status: Review Needed, Type: Enhancement

#137 Get posts controller test / controller API documentation
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/GetPostsController.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/GetPostsControllerTest.java
Labels: Component: Backend, Component: Junit-Testing, Type: Testing

#141 Unit tests: Profile Service & Controller
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/profile/ProfileController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/repository/ProfileRepository.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/ProfileService.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/controller/profile/ProfileControllerTest.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/service/ProfileServiceTest.java
Labels: Component: Junit-Testing, Priority: Medium, Status: Review Needed, Type: Testing

#147 Frontend Implementation: View Controllers Implementation
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/profile/ProfileController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/AdviceViewController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/CreateUserViewController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetPlacesViewController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/IndexViewController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/ProfileViewController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/Profile.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/entity/UserEntity.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/repository/ProfileRepository.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/JoiningCommunityService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/ProfileService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/UserService.java
  practiceapp/src/main/resources/templates/advice.html
  practiceapp/src/main/resources/templates/getjoinedcommunities.html
  practiceapp/src/main/resources/templates/getprofile.html
  practiceapp/src/main/resources/templates/getuserbyname.html
  practiceapp/src/main/resources/templates/index.html
  practiceapp/src/main/resources/templates/saveuser.html
  practiceapp/src/main/resources/templates/searchadvice.html
  practiceapp/src/main/resources/templates/setrandompic.html
  practiceapp/src/main/resources/templates/updateprofile.html
  practiceapp/src/test/java/com/practiceapp/practiceapp/controller/post/CreatePostControllerTest.java
Labels: Component: Frontend, Priority: High, Status: Review Needed, Type: Design

#156 UserServiceTest-ProfileBug-Solved
  practiceapp/src/main/resources/application.yml
  practiceapp/src/test/java/com/practiceapp/practiceapp/service/UserServiceTest.java
Labels: Status: Review Needed

#155 Changing return type of UniversitiesList Api & Unit tests for the apis
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/universitieslist/UniversitiesListController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/utils/UniversitiesListApi.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/GetCommunityControllerTest.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/controller/universitieslist/UniversitiesListControllerTest.java
Labels: Component: Backend, Component: Junit-Testing, Type: Enhancement

#148 Implemented unit test for "Update Post" feature
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/post/UpdatePostController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/PostService.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/controller/post/UpdatePostControllerTest.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/service/PostServiceTest.java
Labels: Component: Junit-Testing, Status: Review Needed

#149 Improvements on Unit Tests for Community, fixed bugs in GetCommunitiesByPublicityViewController and See Post functionality
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetCommunitiesByPublicityViewController.java
  practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetPostsViewController.java
  practiceapp/src/main/resources/templates/communities.html
  practiceapp/src/main/resources/templates/posts.html
  practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/CreateCommunityControllerTest.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/GetCommunitiesByPublicityControllerTest.java
  practiceapp/src/test/java/com/practiceapp/practiceapp/service/CommunityServiceTest.java
Labels: Component: Backend, Component: Junit-Testing, Type: Enhancement

#159 Fixed a bug in community service
  practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
Labels: Component: Backend, Type: Bug
